- name: Current Kubeadm Check
  stat:
    path: $HOME/.kube/config
  register: kube_config

- name: Copy kubeadm-config.yaml
  template:
    src: templates/masters/kubeadm-config.yaml
    dest: /home/pirate/kubeadm-config.yaml
  with_items: "{{ ip }}"
  when: not kube_config.stat.exists

- name: Kubeadm init Master1
  become: yes
  command: kubeadm init --config /home/pirate/kubeadm-config.yaml --upload-certs
  tags: kubeadm_init
  when: not kube_config.stat.exists

- name: Create a directory if it does not exist
  file:
    path: $HOME/.kube
    state: directory
    mode: '0755'
  tags: kubeadm_config
  when: not kube_config.stat.exists

- name: Copy config file
  become: yes
  command: cp /etc/kubernetes/admin.conf /home/pirate/.kube/config
  tags: kubeadm_config
  when: not kube_config.stat.exists

- name: Chown file
  become: true
  file:
    path: /home/pirate/.kube/config
    owner: pirate
    group: pirate
  tags: kubeadm_config
  when: not kube_config.stat.exists

- name: Weave Manfiest Check
  stat:
    path: $HOME/weave.sh
  register: weave

- name: Copy Weave Network Manifest
  template:
    src: templates/masters/weave.sh
    dest: $HOME/weave.sh
  tags: kubectl_network_manifest
  when: not weave.stat.exists

- name: Apply Weave Network Manifest
  command: bash $HOME/weave.sh
  tags: kubectl_apply_weave
  when: not weave.stat.exists

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  tags: kubeadm_command
  when: weave.stat.exists

- name: Copy join command to local file
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: ../roles/kuberpi-role/templates/workers/join-command.sh
  delegate_to: localhost
  tags: kubeadm_command