# tasks file for install prometheus node exporter
- name: Node Exporter Check
  stat:
    path: /etc/sysconfig/node_exporter
  register: node_exporter

- name: Retrieve and Unarchive Binary
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-armv7.tar.gz
    dest: ~/
    remote_src: yes
  when: node_exporter.stat.exists == 'False'

- name: Move binary to /usr/sbin
  become: yes
  command: mv /home/pirate/node_exporter-0.18.1.linux-armv7/node_exporter /usr/sbin/node_exporter
  when: node_exporter.stat.exists == 'False'

- name: Create directory
  become: yes
  file:
    path: /etc/sysconfig
    state: directory
  when: node_exporter.stat.exists == 'False'

- name: Touch file
  become: yes
  file:
    path: /etc/sysconfig/node_exporter
    state: touch
  when: node_exporter.stat.exists == 'False'

- name: Copy systemd File
  become: yes
  template:
    src: templates/nodeexporter.service
    dest: /lib/systemd/system/nodeexporter.service
  when: node_exporter.stat.exists == 'False'

- name: Systemctl daemon-reload
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: nodeexporter
  when: node_exporter.stat.exists == 'False'

- name: Enable nodeexporter service
  become: yes
  systemd:
    name: nodeexporter
    enabled: yes
    masked: no
  when: node_exporter.stat.exists == 'False'
